### ISSUE TITLE
bug username search funtion in postgres honeypot 

### ISSUE THREAD

**Issue by justkhbby** [l3montree-dev/oh-my-honeypot#14]
Error founded in searchUsername function
it gets the error when ..
1.  'database' as username

panic: runtime error: slice bounds out of range [51:28]

goroutine 49068 [running]:github.com/l3montree-dev/oh-my-honeypot/packages/honeypot.searchUsername({0xc009636400, 0x100, 0x400})
	/go/src/app/packages/honeypot/postgresql.go:139 +0xefgithub.com/l3montree-dev/oh-my-honeypot/packages/honeypot.(*postgresHoneypot).Start.func1.1.1({0x8b4c98, 0xc007f5c008})
	/go/src/app/packages/honeypot/postgresql.go:75 +0x1d2
created by github.com/l3montree-dev/oh-my-honeypot/packages/honeypot.(*postgresHoneypot).Start.func1.1 in goroutine 5
	/go/src/app/packages/honeypot/postgresql.go:44 +0x170

**Comment by justkhbby** [comment]
The fixed version was deployed but it got same panic.
